[package]
authors = { workspace = true }
edition = { workspace = true }
name = "zenoh-backend-mongodb"
publish = false
rust-version = { workspace = true }
version = { workspace = true }

[features]
default = ["dynamic_plugin", "zenoh/default"]
dynamic_plugin = []

[lib]
name = "zenoh_backend_mongodb"
crate-type = ["cdylib", "rlib"]

[dependencies]
zenoh = { workspace = true, default-features = false }
zenoh-util = { workspace = true }
zenoh_backend_traits = { workspace = true, default-features = false }
zenoh-plugin-trait = { workspace = true, default-features = false }
async-trait = { workspace = true }
mongodb = "2.8"
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
serde_json = { workspace = true }
futures = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
testcontainers = { version = "0.16", features = ["blocking"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
criterion = "0.5"
proptest = "1"
uuid = { version = "1", features = ["v4"] }

[package.metadata.cargo-machete]
ignored = ["git-version"]

[[bench]]
name = "mongodb_bench"
harness = false
